spring:
  datasource:
    url: jdbc:h2:mem:socialklyp
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  secret: dev-secret-key-social-klyp-dev-only
  accessExpiration: 3600
  refreshExpiration: 7200


b2: # keys for test, expire in 2026-04-16
  key-id: ${B2_KEY_ID}
  key: ${B2_KEY}
  prefix-name-files: social-klyp
  bucket-id: ${B2_BUCKET_ID}


brevo: # keys for test, expire in 2026-04-17
  api-key: ${BREVO_API_KEY}

  sender:
    email: your-email-in-brevo@email.com
    name: Social Klyp

cors:
  allowed-origins: "*"

app:
  init-user:
    enabled: true
    username: admin
    email: admin@dev.com
    password: 12345678