spring:
  datasource:
    url: jdbc:h2:mem:socialklyp
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  secret: dev-secret-key-social-klyp-dev-only
  accessExpiration: 3600
  refreshExpiration: 7200

cors:
  allowed-origins: "*"

app:
  init-user:
    enabled: true
    username: admin
    email: admin@dev.com
    password: 12345678