spring:
  datasource:
    url: jdbc:h2:mem:socialklyp
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  secret: dev-secret-key-social-klyp-dev-only
  accessExpiration: 3600
  refreshExpiration: 7200


b2: # keys for test, expire in 2026-04-16
  key-id: 0054ad00ddb94250000000005
  key: K005f6f3vSV3jZ7btiO+26a1+Gc3uWQ
  prefix-name-files: social-klyp
  bucket-id: 048a8dd0903d8d7b99d40215

cors:
  allowed-origins: "*"

app:
  init-user:
    enabled: true
    username: admin
    email: admin@dev.com
    password: 12345678