spring:
  application:
    name: social-klyp

# if use docker compose comment, or use intellij user profile dev, test or prod
  profiles:
    active: dev

  management:
    endpoints:
      web:
        exposure:
          include: health,info,metrics,prometheus

    endpoint:
      health:
        show-details: always

    prometheus:
      metrics:
        export:
          enabled: true

    metrics:
      tags:
        application: ${spring.application.name}