spring:
  datasource:
    url: jdbc:h2:mem:socialklyp
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  secret: dev-secret-key-social-klyp-dev-only
  accessExpiration: 3600
  refreshExpiration: 7200

storage:
  b2:
    application-key: K005PA8DTZN8QWlh/JiPxgKXvkFGB1c
    key-name: social-klyp-key-read-write
    key-id: 0054ad00ddb94250000000002

    prefix-name-files: social-klyp

    bucket-id: 048a8dd0903d8d7b99d40215
    bucket-name: social-klyp-storage

cors:
  allowed-origins: "*"

app:
  init-user:
    enabled: true
    username: admin
    email: admin@dev.com
    password: 12345678